### ISSUE TITLE
无法登陆。。发送 登陆超级课表没反映

### ISSUE THREAD

**Issue by liyuan-linian** [KonnyakuCamp/SuperCourseTimetableBot#10]
![TIM图片20210509155620](https://user-images.githubusercontent.com/73044843/117564547-20d5a500-b0df-11eb-8ae5-be1c8d31071b.png)

**Comment by StageGuard** [comment]
截图内容不是有效信息
看看配置文件的 `qq` 是否为 `654313176`

**Comment by liyuan-linian** [comment]
是的，还是说我发送的格式不对
![TIM图片20210509160330](https://user-images.githubusercontent.com/73044843/117564746-2384ca00-b0e0-11eb-96d7-f1040c293a14.png)
