### ISSUE TITLE
无法登陆超级课程表

### ISSUE THREAD

**Issue by pf666nb** [KonnyakuCamp/SuperCourseTimetableBot#2]
`无法登录超级课表，原因：kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1151: Encountered an unknown key 'noonTimeBO'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: .....meStr":"2105"}],"noonTimeBO":[{"beginTimeStr":"1215","endTim.....`
数据库使用的是mysql5.7.31

**Comment by StageGuard** [comment]
我淦我没看见issue，这又是脑瘫超级课表api的问题。
一会就修复
![4)EBN@Y0566AX55UIOT_)I9](https://user-images.githubusercontent.com/45701251/105332324-75781180-5c0f-11eb-94ee-c7ef1b2a1b8a.jpg)

**Comment by StageGuard** [comment]
试试刚发布的 0.3.2 版本。

**Comment by pf666nb** [comment]
> 试试刚发布的 0.3.2 版本。

出现了新的问题！
无法登录超级课表，原因：kotlinx.serialization.MissingFieldException: Field 'organization' is required, but it was missing

**Comment by StageGuard** [comment]
> > 试试刚发布的 0.3.2 版本。
> 
> 出现了新的问题！
> 无法登录超级课表，原因：kotlinx.serialization.MissingFieldException: Field 'organization' is required, but it was missing

一会看看

**Comment by StageGuard** [comment]
试试 0.3.3，我去除了所有无用的序列化属性。

**Comment by pf666nb** [comment]
登陆成功后无法同步，使用的 java 为java version "14.0.2"
无法同步课程。原因：java.net.SocketException: Connection reset

**Comment by StageGuard** [comment]
> 登陆成功后无法同步，使用的 java 为java version "14.0.2"
> 无法同步课程。原因：java.net.SocketException: Connection reset

这显然不是 SuperCourseTimetableBot 的问题，有可能你的网络不好？

**Comment by pf666nb** [comment]
> > 登陆成功后无法同步，使用的 java 为java version "14.0.2"
> > 无法同步课程。原因：java.net.SocketException: Connection reset
> 
> 这显然不是 SuperCourseTimetableBot 的问题，有可能你的网络不好？

oh!有时候会有薛定谔的bug
无法同步课程。原因：java.io.IOException: unexpected end of stream on http://120.55.151.61/...
还有就是，如果无法同步课程的话，好像依旧算你登陆了，需要删除用户之后，才能再次同步

**Comment by StageGuard** [comment]
> > > 登陆成功后无法同步，使用的 java 为java version "14.0.2"
> > > 无法同步课程。原因：java.net.SocketException: Connection reset
> > 
> > 
> > 这显然不是 SuperCourseTimetableBot 的问题，有可能你的网络不好？
> 
> oh!有时候会有薛定谔的bug
> 无法同步课程。原因：java.io.IOException: unexpected end of stream on http://120.55.151.61/...
> 还有就是，如果无法同步课程的话，好像依旧算你登陆了，需要删除用户之后，才能再次同步

登录成功的话用户数据会被记录在数据库中，如果登录后课程同步失败了只需要发送同步课程的指令就行了。

**Comment by pf666nb** [comment]
> > > > 登陆成功后无法同步，使用的 java 为java version "14.0.2"
> > > > 无法同步课程。原因：java.net.SocketException: Connection reset
> > > 
> > > 
> > > 这显然不是 SuperCourseTimetableBot 的问题，有可能你的网络不好？
> > 
> > 
> > oh!有时候会有薛定谔的bug
> > 无法同步课程。原因：java.io.IOException: unexpected end of stream on http://120.55.151.61/...
> > 还有就是，如果无法同步课程的话，好像依旧算你登陆了，需要删除用户之后，才能再次同步
> 
> 登录成功的话用户数据会被记录在数据库中，如果登录后课程同步失败了只需要发送同步课程的指令就行了。

感谢帮助，应该是代理问题，导致的网络错误，我刚成功登陆了，只是没有发现同步课程的指令，而且今日课程的指令貌似无效，在未登陆状态下，今日课程指令有效，并提示我未登陆，但是在登陆状态下的，今日课程，插件并没有作出相应
