### ISSUE TITLE
登录无反应

### ISSUE THREAD

**Issue by azi666** [KonnyakuCamp/SuperCourseTimetableBot#22]
![IMG_20210923_102703](https://user-images.githubusercontent.com/57692681/134446466-4367c2fb-1aa3-472a-ad3a-2d07c9bc7c01.jpg)
望作者可否指导下

**Comment by StageGuard** [comment]
现在可以了

**Comment by azi666** [comment]
这个插件能实现群内消息推送么？

**Comment by StageGuard** [comment]
> 这个插件能实现群内消息推送么？

暂不支持

**Comment by azi666** [comment]
希望能支持群内推送，哈哈哈哈，舍友有福同享有难自己当，哈哈哈哈
