### ISSUE TITLE
[bug report]使用readme里提供的实例QQ返回报错

### ISSUE THREAD

**Issue by yimo0908** [KonnyakuCamp/SuperCourseTimetableBot#6]
登录超级课程表后，bot返回消息
`正在登录。。。`  
`登录成功，正在同步你的课程。。。`  
`无法同步课程。原因：kotlinx.serialization.MissingFieldException: Field 'teacher' is required, but it was missing`

**Comment by yimo0908** [comment]
因为我们存在老师和课程不一定对应的情况，所以没有填写每门课的老师，从而导致导入失败。
个人认为，`teacher` 不应该作为一个必须field.。

**Comment by StageGuard** [comment]
可能你们那种情况比较少见，一会看看
(其实还是超级课表的api不规范，teacher 不存在的时候他应该是 null 而不是直接缺失这个属性
